### ISSUE TITLE
New versions of locationforecast and nowcast

### ISSUE THREAD

**Issue by geira** [vramdal/trafikanten-hjemme#37]
Hi,

just a warning that we in a few days will be launching a new version of locationforecast on api.met.no, with a json format and generally more detail. The existing version 1.9 will be terminated in a few months. We are also working on a new version of nowcast which will soon enter beta; the existing version will probably stop working some time after summer.

I also notice from the logs that you are the single most active user of nowcast apart from Yr.no. Every 10 seconds you are downloading locationforecast and nowcast down for your home down to nanometer precision, twice! This is completely unnecessary since the forecasts only change once every hour or 5 minutes respectively, and is explicitly now allowed in our Terms of Service. Both products contain timestamps for the current and following update in the `runended` and `nextrun`, you should store these and not make any new requests until the time indicated in `nextrun` (and then add a minimum 60 sec delay if it hasn't yet been updated). 

You should also truncate coordinates to 3 decimals to improve caching. Also you should send an If-Modified-Since header in the request to avoid downloading a response body which you already have received. If 1000 users started running this code you would generate as much traffic as yr.no! Please update your schedule while porting to the new API endpoints.

**Comment by vramdal** [comment]
Hei Geir, thanks for the notice, this sounds crazy! I'll look into why the fetching interval is not being respected. Shutting down the client for now.
